@if(isset($page_name) && !empty($page_name))
    @switch($page_name)
        @case('books.view')
            @include('contents.cms.books_view')
        @break
        @case('books.add')
            @include('contents.cms.books_add')
        @break
        @case('books.edit')
            @include('contents.cms.books_edit')
        @break
        @case('books.creator')
            @include('contents.cms.books_creator')
        @break
        
        @case('books.detail')
            @include('contents.cms.books_detail')
        @break
        @case('creators.view')
            @include('contents.cms.creators_view')
        @break
        @case('creators.add')
            @include('contents.cms.creators_add')
        @break
        @case('creators.edit')
            @include('contents.cms.creators_edit')
        @break
        @case('creators.detail')
            @include('contents.cms.creators_detail')
        @break
        @case('users.view')
            @include('contents.cms.users_view')
        @break
        @case('users.add')
            @include('contents.cms.users_add')
        @break
        @case('users.edit')
            @include('contents.cms.users_edit')
        @break
        @case('users.detail')
            @include('contents.cms.users_detail')
        @break
        @case('books.error_add_books')
            @include('contents.cms.error.books_error_add_books')
        @break
        @case('books.error_update_books')
            @include('contents.cms.error.books_error_update_books')
        @break
        @case('creators.error_add_creators')
            @include('contents.cms.error.error_add_creators')
        @break
        @case('creators.error_update_creators')
            @include('contents.cms.error.error_update_creators')
        @break
        @case('users.error_add_creators')
            @include('contents.cms.error.error_add_users')
        @break
        @case('users.error_update_creators')
            @include('contents.cms.error.error_update_users')
        @break
    @endswitch
@else
    @include('contents.cms.index')
@endif